# ARC training config

defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

# Data path
data_path: ../Dataset/janus_m15_dataset.parquet

# Hyperparams - Training
global_batch_size: 512

epochs: 15
eval_interval: 3
checkpoint_every_eval: True

lr: 1e-4
lr_min_ratio: 0.1
lr_warmup_steps: 0  # computed in code as 10% of total steps

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 0.01
