# ARC training config

defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

# Data path
data_path: ../Dataset/janus_m15_dataset.parquet

# Hyperparams - Training
global_batch_size: 512

epochs: 20
eval_interval: 2
checkpoint_every_eval: True

lr: 5e-5
lr_min_ratio: 0.1
lr_warmup_steps: 0  # computed in code as 5 epochs in code

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
