
import os
import argparse
import numpy as np
import pandas as pd
from pathlib import Path

def generate_finetune_tasks(input_path: str, output_dir: str, sequence_length: int = 72):
    """
    Generates three finetune datasets for different tasks.

    Tasks:
    1. Directional Classification (Binary): Target = 1 if Close[t+1] > Close[t], else 0.
    2. Dynamic TP/SL (Volatility Regression): Target = [Max_Return_Next_12, Min_Return_Next_12].
    3. Price Forecasting (Scalar Regression): Target = ln(Close[t+1]/Close[t]).
    """
    print(f"Loading data from {input_path}...")
    df = pd.read_parquet(input_path)

    # Ensure necessary columns exist
    required_cols = ['close', 'high', 'low']
    # Check lower case
    df.columns = [c.lower() for c in df.columns]

    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")

    # Prepare features (assuming all columns except targets are features)
    # The prompt implies we use the same features for all tasks.
    # We will just append the target to the dataframe and save it.
    # The FineTuneDataset expects features and target.

    # We need to make sure we don't include look-ahead data in features.
    # The input dataframe is assumed to be the processed features + raw OHLCV.

    # Let's calculate targets.

    # Task 1: Directional Classification
    # Target: 1 if Close[t+1] > Close[t] else 0
    print("Generating Task 1: Directional Classification...")
    df['target_direction'] = (df['close'].shift(-1) > df['close']).astype(int)

    # Task 3: Price Forecasting
    # Target: ln(Close[t+1]/Close[t])
    print("Generating Task 3: Price Forecasting...")
    df['target_log_return'] = np.log(df['close'].shift(-1) / df['close'])

    # Task 2: Dynamic TP/SL
    # Target: [Max_Return_Next_12, Min_Return_Next_12]
    print("Generating Task 2: Dynamic TP/SL...")
    window = 12
    # We need to compute max high and min low over next 12 candles relative to current close
    # Using rolling on reversed dataframe to simulate forward looking window
    indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=window)

    # Compute Max High in next 12
    # We want max(High[t+1]...High[t+12])
    # shift(-1) puts t+1 at t
    high_forward = df['high'].shift(-1)
    low_forward = df['low'].shift(-1)

    # Pass indexer to rolling to ensure forward look
    max_high_next_12 = high_forward.rolling(window=indexer, min_periods=window).max()
    min_low_next_12 = low_forward.rolling(window=indexer, min_periods=window).min()

    # Calculate returns
    df['target_max_return_12'] = (max_high_next_12 - df['close']) / df['close']
    df['target_min_return_12'] = (min_low_next_12 - df['close']) / df['close']

    # Drop NaN values generated by shifting
    # For Task 1 and 3, we lose 1 row at the end.
    # For Task 2, we lose 12 rows at the end.
    df_clean = df.dropna().copy()

    output_dir_path = Path(output_dir)
    output_dir_path.mkdir(parents=True, exist_ok=True)

    # Save Task 1
    task1_path = output_dir_path / "finetune_task1_direction.parquet"
    print(f"Saving Task 1 to {task1_path}...")
    df_clean.to_parquet(task1_path)

    # Save Task 2
    task2_path = output_dir_path / "finetune_task2_volatility.parquet"
    print(f"Saving Task 2 to {task2_path}...")
    df_clean.to_parquet(task2_path)

    # Save Task 3
    task3_path = output_dir_path / "finetune_task3_price.parquet"
    print(f"Saving Task 3 to {task3_path}...")
    df_clean.to_parquet(task3_path)

    print("Done!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=str, required=True, help="Path to input parquet file")
    parser.add_argument("--output", type=str, required=True, help="Directory to save output files")
    args = parser.parse_args()

    generate_finetune_tasks(args.input, args.output)
